### ISSUE TITLE
Создание алгоритма для перемещения объекта 

### ISSUE THREAD

**Issue by Chedening** [Vincent174/lab2#3]

**Comment by Vincent174** [comment]
void __fastcall TForm1::N1Click(TObject *Sender){
	int k = 0, i1 = 0, j1 = 0;
	newgame();
	while(k<16){
		i1 = rand()%4;
		j1 = rand()%4;
		if(StringGrid1->Cells[j1][i1] == 0){
			StringGrid1->Cells[j1][i1] = k;
			k++;
		}
	}
	draw();
}
